export const jwtConstants = {
  secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxOTI1MTEwMCwiaWF0IjoxNzE5MjUxMTAwfQ.xVQEEO789TuZJVLcOdO-axS6fwaxszQLXDfJneAJztg',
};